import Head from "next/head";

// import { usePathname } from "next/navigation";
import Header from "../Header";
import Footer from "../Footer";
import { getTextFromHtml } from "@/app/utils/seo";

const Page = ({
  children,
  CustomHeader,
  CustomFooter,
  title,
  description = "Generated by Nosa",
  descriptionLength = 160,
  keywords = "Nosa",
  author = "Nosa",
  image,
  url,
  locale = "en_US",
  type = "website",
  bg = "white",
  mainContainerStyles = {},
}) => {
  const formattedTitle = title ? `${title}` : "Nosa";
  const formattedDescription =
    description && getTextFromHtml(description, descriptionLength);
  //   const pathname = usePathname();

  const pageContent = (
    <>
      <Head>
        <title>{formattedTitle}</title>
        <meta name="description" content={formattedDescription} />
        <meta name="keywords" content={keywords} />
        <meta name="author" content={author} />
        <meta property="og:title" content={formattedTitle} />
        <meta property="og:description" content={formattedDescription} />
        <meta property="og:image" content={image} />
        <meta property="og:url" content={url} />
        <meta property="og:type" content={type} />
        <meta property="og:locale" content={locale} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={formattedDescription} />
        <meta name="twitter:image" content={image} />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://cdn.jsdelivr.net/npm/mux.js"></script> */}
      </Head>

      {!CustomHeader ? <Header /> : <CustomHeader />}
      <main
        style={{
          backgroundColor: `${bg}`,
          ...mainContainerStyles,
        }}
      >
        {children}
      </main>
      {!CustomFooter ? <Footer /> : <CustomFooter />}
    </>
  );

  return pageContent;
};

export default Page;
