const featuredList = [
  {
    id: "14430ee1-4434-44d1-8e1c-0a01cf46f1a3",
    title: "Janet Pool House",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 399,
    cheapestIn: "5 months",
    distance: {
      walk: "4mins",
      bus: "3mins",
      car: "2mins",
    },
    voucher: {
      type: "Uber",
      Amount: 100,
    },
  },
  {
    id: "0919c4d0-51c3-40e3-a5e8-ae481f04d6c0",
    title: "Stuhome Student Living Heights",
    image: "/assets/images/bedroom.jpg",
    flashSale: true,
    pricePerWeek: 345,
    cheapestIn: "past months",
    distance: {
      walk: "34mins",
      bus: "16mins",
      car: "12mins",
    },
  },
  {
    id: "e140ef0c-fec0-410e-a441-1efa0603d505",
    title: "Flat 49, Forsyth House, Tachbrook Street Oxford Road, London",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 212,
    cheapestIn: "past year",
    distance: {
      walk: "60mins",
      bus: "17mins",
      car: "23mins",
    },
  },
  {
    id: "6f8f455a-f7b5-481d-9575-ad45e0b818c3",
    title: "Janet Pool House",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 400,
    cheapestIn: "1 months",
    distance: {
      walk: "34mins",
      bus: "23mins",
      car: "15mins",
    },
    voucher: {
      type: "Uber",
      Amount: 10,
    },
  },
  {
    title: "Stuhome Student Living Heights",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 340,
    cheapestIn: "6 months",
    distance: {
      walk: "30mins",
      bus: "20mins",
      car: "10mins",
    },
  },
  {
    id: "d1c1315f-b4ec-4c57-abb2-fa4530cc0fbb",
    title: "Flat 49, Forsyth House, Tachbrook Street Oxford Road, London",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 100,
    cheapestIn: "10 months",
    distance: {
      walk: "4mins",
      bus: "3mins",
      car: "2mins",
    },
  },
  {
    id: "ba14e0ef-5f2b-4bae-91ad-9512f52b4d0b",
    title: "Janet Pool House",
    image: "/assets/images/bedroom.jpg",
    flashSale: true,
    pricePerWeek: 399,
    cheapestIn: "5 months",
    distance: {
      walk: "4mins",
      bus: "3mins",
      car: "2mins",
    },
  },
  {
    id: "a8749680-f5e1-4bda-a79a-49dd576cbd6a",
    title: "Stuhome Student Living Heights",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 200,
    cheapestIn: "5 months",
    distance: {
      walk: "4mins",
      bus: "3mins",
      car: "2mins",
    },
  },
  {
    id: "e9e33266-1e10-4b99-aa14-8bb1552b7793",
    title: "Flat 49, Forsyth House, Tachbrook Street Oxford Road, London",
    image: "/assets/images/bedroom.jpg",
    flashSale: false,
    pricePerWeek: 512,
    cheapestIn: "2 years",
    distance: {
      walk: "4mins",
      bus: "3mins",
      car: "2mins",
    },
    voucher: {
      type: "Uber",
      Amount: 80,
    },
  },
];

export default featuredList;
